[package]
name = "delete_update_file"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
env_logger = "0.9.0"
serde = "1"
serde_json = "1"
actix-web = "4.0.0-beta.8"